#+TITLE: Computer Science For Jayden's students
#+AUTHOR: Jayden B
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-bigblow.setup

* Preface:
This book is to teach computer science fundamentals in a classroom environment for kids around the age of 11 - 14 with no prior experince.

It is specifically made for my use-case, but I thought it could be potentialy benificial to others and so I'm releasing it on my github.

The book is still a work in progress as I am activley teaching the curiculum expect things to change. As thing get finalized expect it to get cleaner with a lot less of my own personal anecdotes about my teaching strategy.

** What is this book
This book will also serve as the textbook your students can use!

This curiculum is 16 weeks long, and assumes 120 minutes of instructional time a week.

** Learning Philosophy:
- Holistic understanding of concepts, teach them the why and then the how behind (almost) everything they do. Add complexity slowly and intentionally.
- Show practical applications of programming quickly to keep them engaged. Imagine if all you did when learning programming was leetcodes. That would suck.
- Use professional tools, like the cmd line and git. Build important foudational skills that they'll continue to use regardless of disipline. Not too sure how this'll turn out or how well they'll keep up, but we'll see and adjust.
- Give them oppertunities to explore personal interests, let them make stuff that interest them.

** Learning Goals:
- How computers evolved throughout history.
- What a computer is, the theoretical and physical parts of one.
- The relationship between hardware and software.
- How the internet works.
- How computer logic is represented
- How code turns into binary
- Using the command line
- Git and version control
- Python fundamentals

** Course Format:
Each Week is seperated into different sections:
*** Overview:
- What the students can expect to learn this week
*** Lectures/Readings:
- Videos or Articles for the students to read
*** Labs:
- Work for students to do in class
*** Homework
- Work for students to do outside of class
** Week Breakdown:
*** W1
**** Overview
- Give students a simple overview of the fundamentals and hisotry of computer science
**** Lecture:
[[https://studio.code.org/projects/applab/iukLbcDnzqgoxuu810unLw][Crash Course Computer Science, from the beginning until Binary]]
**** Lab:
[[https://studio.code.org/projects/applab/iukLbcDnzqgoxuu810unLw][Code Studio Binary Game]]
*** w2:
[[https://studio.code.org/projects/applab/iukLbcDnzqgoxuu810unLw][Crash Course Computer Science 6,7,8]]
**** Labs:
- Have kids prepare a presentation about someone important in computer science. For this section, we're having kids focus on picking a Pioneer, we'll make presentations about innovators later.
***** Potential People to make presentations on:
****** Pioneers
- Alan Turning
- Charles Babbage
- Ada Lovelace
- Grace Hopper
- Margaret Hamilton
- Dennis Ritche
- Tim Berners-Lee
****** Innovators
- John Carmack
- Satoshi Nakamoto
- Steve Wozniak
- Linus Torvalds
- Larry Page
- Bill Gates
***** Presentation format:
- Who are they
- What led them to computer science
- What contributions did they make?
- General overview of /how/ they made their contributions (if not too complicated)
- Why were there contributions important?
- Make sure to cite your sources
*** w3:
TBD
*** w4:
TBD
*** w5:
TBD
*** w6:
TBD
*** wn:
TBD
*** w11:
TBD
*** w12:
TBD
*** w13:
TBD
*** w14:
TBD
*** w15:
TBD
*** w16:
TBD
